name: Publish Package
on:
  release:
    types:
      - published
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: [12.x]
    - name: Installing packages
      run: npm install
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: [12.x]
        registry-url: https://registry.npmjs.org/
    - name: Installing packages
      run: npm install
    - name: Publishing Package
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
